---
title: "Trash-Talking Democracy: Why Leaders Erode Their Democracies and How to Stop Them"

---
  
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

by Susan C. Stokes <br/>
Forthcoming

**Why democracy is under assault across the globe by the leaders entrusted to preserve it**

Democracies around the world are getting swept up in a wave of democratic erosion. Since the beginning of the 21st century, two dozen presidents and prime ministers have attacked their countries’ democratic institutions, violating political norms, aggrandizing their own powers, and often trying to overstay their terms in office.

*The Backsliders* offers the first general explanation for this wave. Drawing on a wealth of original research, Susan Stokes shows that increasing income inequality, a legacy of late-20th century globalization, left some countries especially at risk of backsliding toward autocracy. Left-behind voters were drawn to right-wing ethnonationalist leaders in countries like the United States, India, and Brazil, and to left-wing populist ones in countries like Venezuela, Mexico, and South Africa. 

Unlike military leaders who abruptly kill democracies in coups, elected leaders who erode them gradually must maintain some level of public support. They do so by encouraging polarization among citizens and also by trash-talking their democracies: claiming that the institutions they attack are corrupt and incompetent. They tell voters that these institutions should be torn down and replaced by ones under the executive’s control. *The Backsliders* describes how journalists, judges, NGOs, and opposition leaders can put the brakes on democratic erosion, and how voters can do so through political engagement and the power of the ballot box.


[&larr; Back to all books](books.html)