---
title: "Democracy and the Culture of Skepticism: Political Trust in Argentina and Mexico"

---
  
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

by Matthew R. Cleary and Susan C. Stokes <br/>
Russell Sage Foundation, 2006

[Purchase here](https://www.russellsage.org/publications/democracy-and-culture-skepticism-1)


Some theorists claim that democracy cannot work without trust. According to this argument, democracy fails unless citizens trust that their governing institutions are serving their best interests. Similarly, some assert that democracy works best when people trust one another and have confidence that politicians will look after citizen interests. Questioning such claims, *Democracy and the Culture of Skepticism*, by Matthew Cleary and Susan Stokes, suggests that skepticism, not trust, is the hallmark of political culture in well-functioning democracies.

Drawing on extensive research in two developing democracies, Argentina and Mexico, *Democracy and the Culture of Skepticism* shows that in regions of each country with healthy democracies, people do not trust one another more than those living in regions where democracy functions less well, nor do they display more personal trust in governments or politicians. Instead, the defining features of the healthiest democracies are skepticism of government and a belief that politicians act in their constituents' best interest only when it is personally advantageous for them to do so. In contrast to scholars who lament what they see as a breakdown in civic life, Cleary and Stokes find that people residing in healthy democracies do not participate more in civic organizations than others, but in fact, tend to retreat from civic life in favor of private pursuits. The authors conclude that governments are most efficient and responsive when they know that institutions such as the press or an independent judiciary will hold them accountable for their actions.

The question of how much citizens should trust politicians and governments has consumed political theorists since America's founding. In *Democracy and the Culture of Skepticism*, Matthew Cleary and Susan Stokes test the relationship between trust and the quality of governance, showing that it is not trust, but vigilance and skepticism that provide the foundation for well-functioning democracies.


[&larr; Back to all books](books.html)